### ISSUE TITLE
unable to run client

### ISSUE THREAD

**Issue by floripaolo** [bitcraze/crazyflie-clients-python#168]
Hello
I'm running OS X Yosemite.
I tried both Macport and Homebrew.
Everything went ok with installations.
But I keep getting "no such file or directory messages" when trying to run it.

XXXX-MacBook-Air:~ xxxx$ /opt/local/bin/python2.7 bin/cfclient
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'bin/cfclient': [Errno 2] No such file or directory
XXXX-MacBook-Air:~ xxxx$ 

Thanks for help.  :)))

BTW. I changed my laptop recently. On my old one I managed to make it work two years ago. But I can't remember how....

Cheers

P

**Comment by cstanke** [comment]
Hi floripaolo,

What directory are you in when you try to execute "/opt/local/bin/python2.7 bin/cfclient?" From the command line you posted it looks like you are in your User directory (evidenced by the ~ in "XXXX-MacBook-Air:~"). If that's the case, there is likely no "bin" directory in your User folder so the error message is correct. Python can't find bin/cfclient.

You need to 'cd' into the crazyflie-clients-python folder first, and then run the command "/opt/local/bin/python2.7 bin/cfclient"

Regards!

**Comment by floripaolo** [comment]
Paolos-MacBook-Air:~ paolo$ cd /opt/local/bin
Paolos-MacBook-Air:bin paolo$ /opt/local/bin/python2.7 bin/cfclient
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'bin/cfclient': [Errno 2] No such file or directory
Paolos-MacBook-Air:bin paolo$ 

not sure what's wrong....

thanks again

**Comment by cstanke** [comment]
Hi floripaolo,

It looks like you changed into the MacPorts bin directory but you need to be in the "crazyflie-clients-python" directory. Did you download a zip file for the client or did you clone it from GitHub? Where did you clone it to? That's the directory you need to be in that has the "bin" directory with cfclient in it. If you aren't  sure where it is, you can use Spotlight to search for "cfclient" then look at the results on the left-side of the Spotlight window under the "Developer" section.

If you can't figure this out after this message, please start a new thread on the [Bitcraze Crazyflie support forum](http://forum.bitcraze.se/viewforum.php?f=5 "Support"). I'll continue to help you there since this isn't really a cfclient bug.

Regards!

**Comment by floripaolo** [comment]
I managed make it run but now I get this message....

![screen shot 2015-04-30 at 19 10 59](https://cloud.githubusercontent.com/assets/12182291/7418238/b2294d94-ef6c-11e4-90ba-edcafe006b7a.png)

**Comment by cstanke** [comment]
Please create a new thread at http://forum.bitcraze.se/viewforum.php?f=5

**Comment by evoggy** [comment]
Thanks @cstanke for helping out. I'm assuming this was closed in the forum so I'll close it here.
