### ISSUE TITLE
Update install instructions for Mac Ports in README.md

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#206]
Update the install instructions for Mac Ports in the [README.md](https://github.com/bitcraze/crazyflie-clients-python/blob/develop/README.md) to reflect Python 3

**Comment by robrussell** [comment]
The port py34-pyusb named in the Macports section of the instructions doesn't exist. I get:
"Error: Port py34-pyusb not found"
when I try to install it.

**Comment by capriele** [comment]
I've the same problem....
"Error: Port py34-pyusb not found"

**Comment by ataffanel** [comment]
pyusb can easily be installed with pip (I still have to try but ```pip3 install pyusb==1.0.0b2``` should work fine).

However I see a potential bigger problem with pyqt4: there does not seems to be any py34-pyqt4 port available. This would be a bigger problem because pyqt cannot be installed from pip (as far as I know).

If pyqt is not in macport installing dependencies with macport should be marked as not-working in the readme until pyqt is back.

**Comment by ataffanel** [comment]
Closed by PR #219.
