### ISSUE TITLE
Using python client to update firmware?

### ISSUE THREAD

**Issue by mittenchops** [bitcraze/crazyflie-clients-python#217]
I downloaded this [file](https://github.com/bitcraze/crazyflie-firmware/releases/download/2014.12.0/Crazyflie2_2014.12.0_dfu.zip) via instructions [here](https://www.bitcraze.io/2014/12/new-crazyflie-2-0-firmware-and-updated-android-client/)

I saw this in the installation instructions:

```
To start crazyflie in DFU mode follow the procedure:
 1. Disconnect the battery
 2. Press the ON/OFF button
 3. While holding the ON/OFF button, plug the USB to the computer
 4. The LED is first Still, then blink slow, then blinks fast
 5. When the LED blinks fast release the ON/OFF button, Crazyflie 2.0 is now in DFU mode
```

```
Install dfu-utils with your favorite package manager (see bellow). Then start Crazyflie 2.0 in DFU
mode and flash it with:

$ sudo dfu-util -d 0483:df11 -a 0 -D Crazyflie2_2014.12.0.dfu
```

I don't have a radio yet, so assumed I could do this through the GUI.  I am afraid I don't know what that dfu-utils command is doing, but looks frightening, like it might be wrapping a dd my hd with a wrong flag or something.  Does GUI skip over needing to do whatever this is?

So, figuring so...

I keep my CF2.0 connected by USB normally, without restart. 

While connected, bootloader is not available.  So, I click disconnect.

I can now select Connect > bootloader.

I click Initiate bootloader cold boot.
Status: Cannot find a Crazyradio Dongle

OK, I'll ignore that.  I'll just flash.

Crazyflie firmware update
Select a package to flash

Is this: `Crazyflie2_2014.12.0.dfu` (not `flash_crazyflie.bat`, right?)

My questions:

1. How should I go about flashing.  I have to do the DFU mode even with GUI?  
2. What is DFU mode, can this be explained more in the wiki?  As in, I could google to get this this [page](https://wiki.bitcraze.io/projects:crazyflie2:development:dfu), but still don't really understand what the implications of DFU mode are.
3. Is it possible to have the client do something like "restart in DFU mode" so I can be more confident
I got this right than initiating the physical sequence and watching for physical replies?

**Comment by ataffanel** [comment]
Crazyflie 2.0 has 2 CPUs: the nRF51 that handles Bluetooth and radio and the STM32 that handles flight control and usb.

The bootloader we wrote and that is accessed by the GUI is a radio bootloader, it does not support USB. You cannot flash the DFU file with the radio bootloader, you have to flash a ZIP https://github.com/bitcraze/crazyflie-release/releases

1. If you want to update the Crazyflie without a radio you can flash it either with the DFU update script or with the iPhone app. Flashing with the Android app is on the way. There is no DFU support in the GUI.
2. The DFU mode is an integrated bootloader to the STM32, it is not able to update the nRF51. We created the dfu package only to allow people without a radio to update the STM32 anyway.
3. It is technically possible. Though because the DFU bootloader cannot upgrade the nRF51 it is not something we have seen big use for.
