### ISSUE TITLE
Unable to change address

### ISSUE THREAD

**Issue by 4estlaine** [bitcraze/crazyflie-clients-python#220]
While configuring crazyflie2 with the out-of-the-box firmware, the box in which you would change the address in the config menu is greyed out. However, when configuring crazyflies in which I am using a custom version of the firmware, I am able to modify the address. Even so, after "changing" the address in this box and then writing/restarting the crazyflie, I am only able to connect to that crazyflie by using the default address (E7E7E7E7E7). Going back in to the config menu, it shows that the address is changed, but when I connect using a variety of methods (ROS, cfclient, etc.) I am unable to connect unless I again specify the default address. I even tried modifying the custom address in the firmware in the config file and writing that to some other address and then flashing that version of the firmware, but still to no avail.

**Comment by evoggy** [comment]
This should be fixed now, could you give it another try?

**Comment by rbellido1** [comment]
Hi Evoggy,
I have exactly the same problem, unable to change the address, that 4estlaine described above. I checked the cf2config.py and it includes your changes, 2 lines deleted and 1 added. I have tried to used the crazyswarm from USC so this is why I need to change the address of multiple CF2s with crazyradio (No PA). Since your fix is from Jan 2016, i am wondering if you might have another update for this type of issue. Thank you in advance for any help you can provide. Robert
