### ISSUE TITLE
Feature request: activate altitude hold from code

### ISSUE THREAD

**Issue by bowlercaptain** [bitcraze/crazyflie-clients-python#239]
I'm trying to make non-camera-assisted autonomous flight behavior, and in order to prevent the crazyflie from failing to take off or crashing into the ceiling based on battery charge, I would like to use the existing hover mode from a python script. At some point I will use the Accelerometer and gyro to make the PID work in 3d, but for now, if one of the examples turned on the hover mode, that would be awesome. I am searching through the client source to find the activation code from the GUI, but no success yet.

**Comment by fredg02** [comment]
Providing an example script is difficult, because it's unsafe to use altitude hold without having control of the Crazyflie. Controlling the Crazyflie would require a joystick control loop, etc and therefore be a long example script.

You basically have to set the parameter "flightmode.althold" to 1.
E.g. ```self.helper.cf.param.set_value("flightmode.althold", 1)```

Please be aware that when you use altitude hold you also have to send different thrust values:
* You need to send "32767" to hold the altitude.
* Values lower than "32767" will lead to a descent.
* Values higher than "32767" lead to a ascent.

Look for "althold" and "_limit_thrust" in the source code.
Find more info here:
* https://wiki.bitcraze.io/projects:crazyflie:firmware:altitude_hold
* https://forum.bitcraze.io/viewtopic.php?f=6&t=523

**Comment by islamoc** [comment]
Hello any updates on this ? because for me it is not working

**Comment by ataffanel** [comment]
@islamoc Altitude-hold has been fixed recently in the firmware. If you still have problems please open a ticket with more explanation about the problem.

For now I close this ticket.
