### ISSUE TITLE
MapQuest on GPS tab not working anymore

### ISSUE THREAD

**Issue by bracco23** [bitcraze/crazyflie-clients-python#266]
Hello,
Today I tried to use the GPS tab and, instead of the map, a blank page with some words appreared. 
![schermata del 2016-10-21 09 59 13](https://cloud.githubusercontent.com/assets/9967447/19591013/3c9eaeea-9775-11e6-8a2b-a8037b0c8b72.png)

At the link provided there is a blog post, here it is.

http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

I just thought you had to know.

**Comment by ataffanel** [comment]
Hi, thanks for reporting! This is something we need to solve somehow. We where using marble previously and maybe this would be a solution.

**Comment by StylusEater** [comment]
@ataffanel Do you have a link to the previous work on the integration as this would be a useful tool to have and maybe one of us could contribute?

**Comment by ataffanel** [comment]
@StylusEater I assume you are refering to the marble-based GPS tab, it looked like that: https://github.com/bitcraze/crazyflie-clients-python/blob/2df602c9ae1a20caf897bcf75b022a084a0332b4/lib/cfclient/ui/tabs/GpsTab.py

The problem we had with it is that the python binding for marble had to be compiled since it was not considered stable by the project and was not part of standard distribution packet. I do not know if that has been solved.

**Comment by ataffanel** [comment]
Since the GPS tab is causing trouble with portability (first to QT5 and now apparently it prevents running on  Ubuntu 16.10), I disabled it.

Lets re-enable the GPS tab when we have found a way to display a map in PyQT.

**Comment by jonasdn** [comment]
Is a GPS tab still something we want to have? @ataffanel

**Comment by jonasdn** [comment]
Remove any and all trace of the GPS tab in code.
