### ISSUE TITLE
"Write to anchors" is very inconsistent

### ISSUE THREAD

**Issue by benkuper** [bitcraze/crazyflie-clients-python#340]
"Write to anchors" in the Loco tab does not work all the times, and some times it does not work at all : some values are updated, not others, and there is no way to really know what worked and what didn't.

**Comment by krichardsson** [comment]
This functionality is a bit complex and has a few issues. This comment is intended as an explanation of what is happening to make it easier to understand. The functionality can probably be improved in multiple ways.

When the "write to anchors" button is clicked the intended flow is something like:
1. The python client issus a write of anchor positions (using the python lib) that is sent to the Crazyflie (usually via Crazyradio)
1. The Crazyflie acts as a bridge and broadcasts the message on to the anchors using the UWB radio on the LPS deck
1. The anchor updates its position and stores it in memory
1. The anchor uses the new position and sends it as a part of outgoing UWB messages
1. The Crazyflie receives the anchor position through the LPS deck and stores it locally
1. The Client polls anchor positions from the Crazyflie (every 5 seconds when the LPS tab is open) using the memory sub system in the python lib
1. The Client uses the anchor positions received from the Crazyflie to set the color of the anchor position input boxes in the LPS tab. If the value in an input boxe matches the value received, the background is set to green, otherwise red.

So to conclude, when clicking the "Write to anchors" button, the anchor position input boxes should turn green within 5 seconds.

There are two main sources of errors:
* All anchors did not receive the position message from the LPS deck
  * Move closer to the anchor(s) that was not updated and write again
* The updated position is not received in the client due to a bug in the memory sub system (bitcraze/crazyflie-lib-python#78). 
  * Restart the client. Note that the write part of the operation might have succeeded but that there is no feedback in the UI.

**Comment by benkuper** [comment]
Thank you for that !
I restarted many times the client without success, so i guess it's a drone<>node communication problem.
Is there a way to make this more stable in cases some anchors did not get the message ?

Also, i'm trying to implement this feature in LaMoucheFolle, but can't seem to find the good packet structure to send... so far, i've got that :
 
const crtp header;
uint8_t lppShortPacket;
uint8_t nodeId;
uint8_t lppTypePosition;
float x;
float y;
float z;

which would translate to :
 [byte] 0x06,  [byte] 1, [byte] 0x02, [byte] <nodeId>, [byte] 1,  [float] x, [float] y, [float] z

but it doesn't seem to work.. is it the good structure ?

**Comment by ataffanel** [comment]
- How does it fail, does the position values stays red or are they always white? 
 - Does it change anything if you get close to the anchors?
 - If your run in TDoA mode, do you see the TX led blinking on the Crazyflie when you send the positions?

The way to know if the anchor got the message is to read back the position and compare it to the request, this is indicated in the client by switching the field back to green. One could make it more automatic but since setting the position might require to user to more around to get close to the anchors we figured that the best would be to give all the info to the user (with the fields color) rather than having an automatic algorithm.

For the packet the port looks wrong, according to [the wiki](https://wiki.bitcraze.io/doc:crazyflie:crtp:localization#localization_crtp_port) you should send it to port 6 channel 1 so header should be 0x61 instread of your first two byte. A good way to debug is to switch one of your LPS node in sniffer mode and to look if the LPP packet is sent by the Crazyflie.

**Comment by benkuper** [comment]
- The values are staying red
 - It seems a bit better when i get close to the anchor
 - I didn't check the tx led on the drone, i'll tell you when i test it again

I don't really understand why the drone have to be close the anchors, since it is able to receive the data from the anchors from anywhere.. ? is it another communication pipe ?

For the packet structure, i'm sorry for the misunderstanding, the header constructor in crazyflie_cpp is like that :

 ```
constexpr crtp(uint8_t port, uint8_t channel)
    : channel(channel)
    , link(3)
    , port(port)
  {
  }

  crtp(uint8_t byte)
  {
    channel = (byte >> 0) & 0x3;
    link    = (byte >> 2) & 0x3;
    port    = (byte >> 4) & 0xF;
  }
```

The external position packet constructor looks like that :

```
crtpExternalPositionUpdate(
    float x,
    float y,
    float z)
    : header(0x06, 0)
    , x(x)
    , y(y)
    , z(z)
  {
  }
```
and my setNodePos packet constructor looks like that  :
	crtpSetNodePosRequest(
		uint8_t nodeId,
		float x,
		float y,
		float z //z is up
	)
		: header(0x06, 1) //Port CrtpPort.LOCALIZATION and Channel 1 (from lib-python code)
		, lppShortPacket(0x02) //from lib-python code
		, nodeId(nodeId)
		, lppTypePosition(1) //from lib-python code
		, x(x)
		, y(y)
		, z(z)
	{
	}

So i guess it should work, right ?
When i send this packet, the Led-deck flash orange, is it a known behaviour for you ?

**Comment by krichardsson** [comment]
Is this working for you now?
Another option is to use the script in https://github.com/bitcraze/lps-node-firmware, tools/lpp/set_positions.py to set anchor positions.
