### ISSUE TITLE
Environment Variable equivalent for CFClient?

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/crazyflie-clients-python#359]
Hi,

I'd like to force CFClient to enable LED Ring & Loco deck

I had to make some modifications and removed the I2C memory
So now CFClient cannot detect that I haev locodeck and Led ring installed

The way I fixed my problem is to just hard-code the checking to true
For example:
![image](https://user-images.githubusercontent.com/5380731/49430333-b15c7c80-f7e5-11e8-95c5-2cc916eb4856.png)

It's not a long term solution 
So I'd like to be on track with the main repo and contribute 
allowing users to force the client to run for certain decks (mainly to by pass I2C mem detections)

What's the best way to do this?

Thanks

**Comment by ataffanel** [comment]
I think the best way to do this is to use the params instead of the memory ID: 
![image](https://user-images.githubusercontent.com/6381499/49579457-8d677b00-f94c-11e8-8708-6c13c41bfde0.png)

these params are set to 1 when the deck driver is enabled, either by a deck memory or when the driver is forced. Since you want to communicate with these driver checking if they are enabled seems to be the proper way to go.

Maybe the best would be to have a 'deck' module in Crazyflie that fetches all the deck parameter values at startup and that allows to write: 
``` python
if self.helper.cf.deck.is_initialized("bcLedRing"):
```

Do you think this would solve your use-case?

**Comment by NicksonYap** [comment]
Oh wow, thanks!

Would this be a good/better solution to merge with master? 
I can change all onewire detection to only rely on the deck params, since crazyflie itself will do the detection
If ok, I'll test and sumbit a PR

**Comment by ataffanel** [comment]
Yes it you implement the detection with param it is definitely something I would like to merge!

**Comment by NicksonYap** [comment]
@ataffanel 

Apparently this will do: 

```py
 if bool(self.helper.cf.param.values["deck"]["bcLedRing"]):
```

Is this acceptable?

I've originally misunderstodd your statement, thinking that the "deck" module is already available
I didn't get how the "self.helper.cf" is created

**Comment by ataffanel** [comment]
Hi,
sorry for the late answer.
If using the param works it is great. One problem might be that just after connection not all the param values have been read so this might cause a problem.
No problem with mapping using the wiki info, we have all the deck so we can check them before merging the PR.
