### ISSUE TITLE
Why is NumPy version specified in setup.py restrictive?

### ISSUE THREAD

**Issue by jpreiss** [bitcraze/crazyflie-clients-python#526]
`setup.py` gives the version specifier `~=1.19.2` for NumPy:

https://github.com/bitcraze/crazyflie-clients-python/blob/8722dd5bd2c16a2c201eb116fec3ad1653dec75f/setup.py#L142

According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release), this is equivalent to

    >= 1.19.2, == 1.19.*

This is fairly restrictive. Why was it chosen instead of `>= 1.19.2`?

If cfclient depends on a deprecated feature of NumPy, I can make a PR adding an explanatory note in `setup.py` for others who encounter this in the future.

**Comment by ataffanel** [comment]
The main reason is that ~= usually means "compatible version" for semantic versioning which is usually good practice.

Apparently numpy does [not use semantic versioninig](https://numpy.org/doc/stable//user/depending_on_numpy.html) and can break API in minor release, so our current version specification is the safest.

What about bumping the cflib version to the current latest numpy version "~=1.21.0"? Numpy promise to keep function for 2 minor release with a warning so ">=1.21.0,<1.24" would also work for me.

We have had a lot of random bug due to random dependency version over the years so I am not so comfortable opening the versions too wide :-). Instead we should likely have a process of manually bump up dependencies in a controlled manner at regular interval.

**Comment by jpreiss** [comment]
That makes sense. I didn't realize numpy breaks the api for minor versions.

No need to change anything for our sake - since we still support python 2.7, we need to be compatible with old versions of numpy anyway.

**Comment by ataffanel** [comment]
Ok sounds good, but, will it break something for you if we do bump the version? I think we likely use very common, and so very stable, APIs in numpy, so we should be able to do something like ">=1.19.2,<1.24" however since we do not support python 2.7 anymore in the lib, maybe it does not make any difference?

**Comment by jonasdn** [comment]
We could merge a PR like that and see if the crazylab catches anything?
