### ISSUE TITLE
client does not install on linux with python 3.11

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#660]
Found on ubuntu with python 3.11

There seems to be a problem with the dependency to pyzmq in setup.py `pyzmq~=22.3`
pyzmq 25.0 installs, but I have not tested if it works. 

Workaround:
For normal client usage zmq is not used and should cause any problems also if it does not work anyway.
In `setup.py` change `'pyzmq~=22.3',` to `'pyzmq~=25.0',`

**Comment by razmy-hathy** [comment]
Which setup.py ?

**Comment by krichardsson** [comment]
You need to install it from source (git clone this repository), see [the docs](https://github.com/bitcraze/crazyflie-clients-python/blob/master/docs/installation/install.md)

This file: https://github.com/bitcraze/crazyflie-clients-python/blob/master/setup.py

**Comment by razmy-hathy** [comment]
Yes, I change it and install it from source. it is working now. Thanks for you support.

**Comment by razmy-hathy** [comment]
Do I need to follow the instruction given below. I don't want to reinstall the x86 brew has I already used brew install other softwares. Please explain.

Apple M1
On Apple M1 Macs, care should be taken to use the X86 version of Brew since not all required dependencies compiles for the native arm64 architecture of the M1 macs. This can be done by using the arch commands when installing brew:

# Installing brew for x86_64, it will be installed in /usr/local by default
arch --x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Now we have to use brew and then python from /usr/local ...
arch --x86_64 brew install python@3.9 libusb
# The arch command is not required anymore since everything brew installed are x86 executables

**Comment by krichardsson** [comment]
Please [start a new discussion](https://github.com/orgs/bitcraze/discussions), it does not fit the title "client does not install on linux with python 3.11" of this issue

**Comment by knmcguire** [comment]
So our general conclusion from the triage meeting is: Let's bump up the version of pyzmq and see what happens. We don't expect this to fail but we got to test it out first.
