### ISSUE TITLE
Missing Qualisys tab on macOS

### ISSUE THREAD

**Issue by NageshEranki** [bitcraze/crazyflie-clients-python#717]
Hi 

I use the client and the qualisys python SDK installed from source on my MacBook Air M3. Everything is installed in a conda environment. I do not see the 'Qualisys tab' in the drop down menu.

Any fixes?

Thanks

**Comment by ToveRumar** [comment]
Hi!
There is nothing wrong with your setup. 

This tab was removed due to its limited usage, as external software from the mocap provider is necessary to operate the system anyway.

We may reintroduce some mocap features in the future, but there are no current plans to do so.

If you need this functionality, you will need to revert your client version to 2023.6.
